# Generated by Django 2.2.27 on 2022-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elephant',
            fields=[
                ('event', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=32)),
                ('lon', models.CharField(max_length=32)),
                ('lat', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
