# Generated by Django 2.2.27 on 2022-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220417_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_data',
            fields=[
                ('event', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=32)),
                ('lon', models.CharField(max_length=32)),
                ('lat', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Whale',
            fields=[
                ('event', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=32)),
                ('lon', models.CharField(max_length=32)),
                ('lat', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
